<?php $reply = $this->getCurrentReply(); ?>
<div id="inbox_edit_reply" class="section inbox_step">
    <form id="commentreplyForm" method="post" class="form-horizontal" onsubmit="return false;">
        <div class="buttons">
            <button type="button" onclick="inbox.closeCommentReply(<?php echo $reply->getParentId(); ?>)" class="delete left"><i class="icon-arrow-left"></i></button>
            <div class="clear"></div>
        </div>
        <div>
            <div class="form-group">
                <div class="col-md-12">
                    <?php echo $reply->getMessage(); ?>
                </div>
            </div>
        </div>
        <div id="post_reply">
            <div class="form-group">
                <div class="col-md-12">
                    <textarea id="message" name="message" class="replace-with-ckeditor"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <button class="default_button right" onclick="reply.postReply(<?php echo $reply->getParentId(); ?>)"><?php echo $this->_("OK"); ?></button>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <input type="hidden" id="parent_id" name="parent_id" />
    </form>
</div>