<?php

$application = $this->getApplication();
$option_value = $this->getOptionValue();
$value_id = $option_value->getId();

$form_message = new Inbox_Form_Message();
$form_message->setValueId($option_value->getId());

$form_message_option = new Inbox_Form_MessageOption();

$form_option = $this->getFormOption();

$delete_form = new Inbox_Form_Message_Delete();

$messages = $this->getMessages();

$customers = $this->getCustomers();
$customer_count = sizeof($customers);

?>

<div id="inbox_view">
    <div class="feature-block-add">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo __("Inbox"); ?>
            <button type="button" class="feature-toggle-add toggle_design color-blue pull-right bt-header-right btn">
                <i class="fa fa-plus"></i>
            </button>
        </h3>
    </div>

    <div class="feature-block-create">
        <h3 class="title-editor no-border-radius title-feature-indent">
            <?php echo __("Send a message"); ?>
        </h3>

        <!-- Form inbox message -->
        <div class="container-fluid inbox-form-step" data-step="1">
            <?php echo $form_message; ?>
        </div>
        <!-- /Form inbox message -->


        <!-- User list select -->
        <div class="container-fluid inbox-form-step" data-step="2" style="display: none;">

            <form id="form-inbox-message-option" class="form sb-form feature-form form-horizontal">

                <fieldset id="fieldset-navinboxmessage-option" class="sb-nav">
                    <dl>
                        <div class="sb-back-button">
                            <button id="goto-step-1" name="sbback" id="sbback" type="button" class="btn pull-left default_button color-blue">
                                <i class="fa fa-chevron-left icon icon-chevron-left"></i>
                            </button>
                        </div>
                        <div class="sb-save-info-button">
                            <input type="submit" name="<?php echo __js("Send message"); ?>" id="OK" value="<?php echo __js("Send message"); ?>" class="btn pull-right default_button color-blue">
                        </div>
                    </dl>
                </fieldset>

                <div class="form-group sb-form-line">
                    <label for="send_at" class="sb-form-line-title col-md-12 optional">
                        <?php echo __("Send my message at this date (leave empty for instant sending):"); ?>
                    </label>
                    <div class="col-md-4">
                        <input type="text" name="send_at" id="send_at" value="" data-datetimepicker="datetimepicker" class="sb-input-send_at input-flat">
                    </div>
                    <div class="sb-cb"></div>
                </div>
                <div class="form-group sb-form-line form-group-checkbox">
                    <div class="control control--checkbox">
                        <input type="checkbox" name="send_to_all" id="send_to_all" value="1" class="sb-form-checkbox flatbox">
                        <div class="color-blue control__indicator"></div>
                    </div>
                    <label for="send_to_all" class="for-checkbox sb-form-line-title optional">
                        <?php echo __("Send to all"); ?>
                    </label>
                </div>
                <div class="form-group sb-form-line form-group-checkbox">
                    <div class="control control--checkbox">
                        <input type="checkbox" name="send_notif" id="send_notif" value="1" class="sb-form-checkbox flatbox">
                        <div class="color-blue control__indicator"></div>
                    </div>
                    <label for="send_notif" class="for-checkbox sb-form-line-title optional">
                        <?php echo __("Send a push notification to inform users"); ?>
                    </label>
                </div>
            </form>

            <form id="inbox-customer-form">
                <table id="inbox-customer-list" class="table content-white-bkg sb-pager">
                    <thead>
                    <tr class="border-blue">
                        <th></th>
                        <th class="sortable numeric" style="min-width: 40px;"><?php echo __("ID"); ?></th>
                        <th class="sortable" style="width:34%;"><?php echo __("Customer"); ?></th>
                        <th class="sortable" style="width:28%;"><?php echo __("E-mail"); ?></th>
                        <th class="sortable date" style="width:25%;"><?php echo __("Registration date"); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($customers as $customer): ?>
                        <tr class="sb-pager">
                            <td>
                                <div class="col-md-7 control control--checkbox">
                                    <input type="checkbox" name="customer_id[]" value="<?php echo $customer["customer_id"]; ?>" />
                                    <div class="color-blue control__indicator"></div>
                                </div>
                            </td>
                            <td><?php echo $customer["customer_id"]; ?></td>
                            <td><?php echo $customer["firstname"], " ", $customer["lastname"]; ?></td>
                            <td><?php echo $customer["email"]; ?></td>
                            <td data-timestamp="<?php echo $customer["registration_timestamp"] ?>">
                                <?php echo datetime_to_format($customer["registration_date"]); ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5"><?php echo __("No matching users.") ?></td>
                        </tr>
                    </tfoot>
                </table>
            </form>
        </div>
        <!-- /User list select -->

    </div>

    <?php if($messages && $messages->count() > 0): ?>
        <div class="feature-block-list">
            <div class="margin-top">
                <h3 class="title-editor no-border-radius title-feature-indent">
                    <?php echo __('Manage messages'); ?>
                    <button type="button" class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                        <i class="fa fa-chevron-down"></i>
                    </button>
                </h3>
                <div class="container-fluid first-row-feature feature-manage-items">
                    <table id="inbox-thread-list" class="inbox-table table content-white-bkg sb-pager">
                        <thead>
                        <tr class="border-blue">
                            <th class="sortable" style="width:25%;"><?php echo __("Title"); ?></th>
                            <th class="sortable" style="width:35%;"><?php echo __("User"); ?></th>
                            <th class="sortable" style="width:35%;"><?php echo __("Most recent response"); ?></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($messages as $message): ?>

                            <tr id="message_manage_element_<?php echo $message->getMessageId(); ?>" class="message-manage-element sb-pager">
                                <td><?php echo $message->getTitle(); ?></td>
                                <td><?php echo sprintf("%s %s - %s", $message->getCustomerFirstname(), $message->getCustomerLastname(), $message->getCustomerEmail()); ?></td>
                                <td>
                                    <?php if(!!$message->getScheduled()): ?>
                                        <b><?php echo __("Scheduled for %s", datetime_to_format($message->getSendAt())) ?></b>
                                    <?php else: ?>
                                        <?php echo datetime_to_format($message->getLatestUpdate()); ?>
                                    <?php endif; ?>
                                </td>

                                <?php if(!$message->getScheduled()): ?>
                                <td class="edit-action open-edit inbox-reply" data-clear="true" data-id="message_<?php echo $message->getMessageId(); ?>" data-form-url="<?php echo __path("/inbox/message/loadform", array("message_id" => $message->getMessageId(), "customer_id" => $message->getCustomerId(), "value_id" => $value_id)); ?>">
                                    <span class="inbox-replies"><?php echo $message->getMessageCount(); ?></span>
                                    <i class="inbox-replies-icon fa fa-comments-o"></i>
                                </td>
                                <?php else: ?>
                                <td></td>
                                <?php endif; ?>
                                <td class="delete-action">
                                    <?php
                                        $delete_form->setAttrib("data-rowid", "message_manage_element_".$message->getMessageId());
                                        $delete_form->getElement("message_id")->setValue($message->getMessageId());
                                        $delete_form->getElement("customer_id")->setValue($message->getCustomerId());

                                        echo $delete_form;
                                    ?>
                                </td>
                            </tr>
                            <tr class="edit-form" data-id="message_<?php echo $message->getMessageId(); ?>" style="display: none;">
                                <td colspan="5">
                                    <p class="close-edit" data-clear="true" data-id="message_<?php echo $message->getMessageId(); ?>">
                                        <i class="fa fa-times"></i><?php echo __("Close") ?>
                                    </p>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    <?php endif; ?>

    <div class="feature-block-list">
        <div class="margin-top">
            <h3 class="title-editor no-border-radius title-feature-indent">
                <?php echo __('Options'); ?>
                <button type="button" class="toggle_design color-blue pull-right bt-header-right btn feature-toggle-items">
                    <i class="fa fa-chevron-down"></i>
                </button>
            </h3>
            <div class="container-fluid first-row-feature feature-manage-items" style="display: none;">
                <?php echo $form_option; ?>
            </div>
        </div>
    </div>

    <div>
        <?php echo $this->importBackground($option_value); ?>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {

        var affixFieldset,
            contentElement,
            containerBlocks,
            header,
            sections_html;
        window.initialStartAt = 1500;

        bindForms("#inbox_view");

        $("#form-inbox-message").on("submit", function(event) {
            event.preventDefault();

            gotoStep2();

        });

        $("#form-inbox-message-option").on("submit", function(event) {
            event.preventDefault();

            if($("input[name='customer_id[]']:checked").length == 0) {
                alert("<?php echo __js("You must select at least one user.") ?>");
                return;
            }

            loader.show("sb-features");

            var form = $(this);
            var datas = $("#form-inbox-message, #form-inbox-message form, #inbox-customer-form, #form-inbox-message-option").serializeArray();

            $.ajax({
                url: $("#form-inbox-message").attr("action"),
                method: "POST",
                dataType: "json",
                data: datas,
                success: function(data) {
                    if(data.success) {
                        feature_form_success(data.message || data.success_message);
                        feature_reload();
                    } else if(data.error) {
                        handleFormError(form, data);
                    }

                    loader.hide("sb-features");
                },
                error: function(data) {
                    var response = $.parseJSON(data.responseText);
                    if(response.message != "") {
                        handleFormError(form, response);
                    } else {
                        feature_form_error("An error occured, please try again.");
                    }

                    loader.hide("sb-features");
                }
            });
        });

        $("#goto-step-1").on("click", function() {
            gotoStep1();
        });

        $("#inbox-thread-list").sbpager({
            with_search: true,
            search_placeholder: '<?php echo __js("Search ...", "'") ?>',
            callback_goto_page: function() {
                $("table.sb-pager tr.edit-form[data-id]").hide()
            }
        });

        $("#inbox-customer-list").sbpager({
            with_search: true,
            search_placeholder: '<?php echo __js("Search ...", "'") ?>'
        });

        // Toggle all user checkboxes
        $("#send_to_all").on("click", function() {
            var el = $(this);
            $("#inbox-customer-form").find("input[name='customer_id[]']").prop("checked", el.prop("checked"));
        });

        // Untick select all, if one out
        $("#inbox-customer-form").find("input[name='customer_id[]']").on("click", function() {
            var el = $(this);
            if(!el.prop("checked")) {
                $("#send_to_all").prop("checked", false);
            } else if($("input[name='customer_id[]']:checked").length == $("input[name='customer_id[]']").length) {
                $("#send_to_all").prop("checked", true);
            }
        });

        var step1 = $("div.inbox-form-step[data-step='1']");
        var step2 = $("div.inbox-form-step[data-step='2']");

        var gotoStep1 = function() {
            $("#form-inbox-message").find("textarea.richtext").each(function() {
                var el = $(this);
                el.ckeditorGet().destroy();
                refreshCkeditor(el, "cms");
            });

            step1.slideDown();
            step2.slideUp();
        };

        var gotoStep2 = function() {
            if($("#form-inbox-message input[name='title']").val().trim() == "") {
                alert("<?php echo __js("Message title is required and can't be empty.") ?>");
                return false;
            }

            step1.slideUp();
            step2.slideDown();
        };

        var scrolling_submit = $("#fieldset-navcms input[type='submit']");

        setTimeout(function() {
            affixFieldset = $("#fieldset-navcms");
            affixFieldset.attr("data-affixed", false);
            contentElement = $("#inbox_view");
            containerBlocks = $("#sections_html_container");
            header = $("#inbox_view").find("h3").first();
            sections_html = $("#sections_html").offset();
            window.initialStartAt = sections_html.top;

            $(window).scrolled(function() {

                var contentOffset = contentElement.offset();
                var currentScroll = $(window).scrollTop();
                var fixedwidth = contentElement.width();
                var scrollStartAt = window.initialStartAt;

                /** Bottom hit */
                var bottomLimit = currentScroll + affixFieldset.outerHeight();
                var contentBottom = contentElement.height() + contentOffset.top;
                var newTop = contentBottom - currentScroll - affixFieldset.outerHeight();

                /** Styles */
                var styleAffix = ""+
                    "position: fixed !important;"+
                    "width: " + fixedwidth + "px;"+
                    "z-index: 5000;"+
                    "margin: 0;"+
                    "margin-left: -15px;"+
                    "padding: 15px 15px 0 15px;"+
                    "background: white;"+
                    "box-shadow: 0 0 2px lightgrey;"+
                    "border-bottom: 1px solid lightgrey;";

                if((currentScroll > scrollStartAt) && (bottomLimit < contentBottom)) {
                    affixFieldset.attr("style", styleAffix + "top: 0px !important;");
                    affixFieldset.attr("data-affixed", true);
                    containerBlocks.attr("style", "margin-top: " + (affixFieldset.outerHeight()+ 15) + "px;");
                    scrolling_submit.show();
                } else if (bottomLimit > contentBottom) {
                    affixFieldset.attr("style", styleAffix + "top: " + newTop + "px !important;");
                    affixFieldset.attr("data-affixed", true);
                    scrolling_submit.show();
                } else {
                    affixFieldset.removeAttr("style");
                    affixFieldset.attr("data-affixed", false);
                    containerBlocks.removeAttr("style");
                    scrolling_submit.hide();
                }

            });
        },1100);

        $(document).on("click", "#inbox_view .feature-toggle-add", function() {
            setTimeout(function() {
                sections_html = $("#inbox_view #sections_html").offset();
                window.initialStartAt = sections_html.top;
            },100);
        });

    });
</script>

<?php
echo $this->getLayout()
    ->addPartial("cms_javascript", "Core_View_Default", "cms/application/page/edit/block_v2/javascript.phtml")
    ->setOptionValue($option_value)
    ->toHtml();
?>

<style type="text/css">
    table.inbox-table td {
        vertical-align: middle;
    }

    .edit-action {
        cursor: pointer;
    }

    td.inbox-reply {
        min-width: 50px !important;
    }

    .inbox-replies {
        display: inline-block;
    }

    .inbox-replies-icon {
        display: inline-block;
    }


    td .control--checkbox {
        margin: 0 !important;
        height: 20px !important;
    }

    td .control--checkbox input[type='checkbox'] {
        width: 20px;
        height: 20px;
        top: 0;
        left: 0;
    }

    #form-inbox-message-option {
        margin-top: 20px;
    }

    #form-inbox-message-option .control--checkbox {
        float: left;
        width: 30px;
    }

    #form-inbox-message-option label.for-checkbox {
        float: left;
    }
</style>
